### ISSUE TITLE
Cannot run `yarn` in `app` folder.

### ISSUE THREAD

**Issue by D4nte** [comit-network/app#33]
When following the readme instructions I am getting an error to install the taker. Are you aware of this issue?

```
▶ cd ./app
▶ yarn
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
$ yarn electron-rebuild
yarn run v1.22.4
$ node -r ../internals/scripts/BabelRegister.js ../internals/scripts/ElectronRebuild.js
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module '@babel/register'
Require stack:
- /Users/froyer/src/comit-network/app/internals/scripts/BabelRegister.js
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/froyer/src/comit-network/app/internals/scripts/BabelRegister.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/froyer/src/comit-network/app/internals/scripts/BabelRegister.js',
    'internal/preload'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by yosriady** [comment]
Yes, you need to run `yarn` in the root folder as well. I'll update the documentation.
